public enum Deathrattles {
    NONE,
    SUMMON_TWO_IMPS,
    SUMMON_ONE_IMP,
    SUMMON_GOLEM,
    SUMMON_EGG,
    SUMMON_TWO_HYENA,
    SUMMON_RAT_TAUNT,
    SUMMON_AND_BUFF_MECH_6_6,
    BUFF_1_1_EVERYTHING,
    ONE_DAMAGE_ALL,
    ONE_DAMAGE_ALL_TWICE,

    BOMB,
    BOMB_TWICE,
    SUMMON_TWO_MECH_DIED


}
